#!/bin/bash

if (($# == 0)); then
  echo "Usage: cybex-launch-or-focus-webapp [window-pattern] [url-and-flags...]"
  exit 1
fi

WINDOW_PATTERN="$1"
shift
LAUNCH_COMMAND="cybex-launch-webapp $@"

exec cybex-launch-or-focus "$WINDOW_PATTERN" "$LAUNCH_COMMAND"